### ISSUE TITLE
Tokenization 

### ISSUE THREAD

**Issue by beareality** [mrwellmann/Unity-Text-To-Seech-with-Sentis#1]
Thank you for your Sentis Example Project. The tokenization is done right, i just changed the output string a bit and parsed it as int array.

In TokenizerRunner.cs:
```
// Get the output from the StringWriter
            string output = stringWriter.ToString();
            output = output.Substring(1, output.Length - 3);
            return output;
```

In TestTextToSpeech.cs:
```
// Convert input text to tensor.
        tokenizedOutput = tokenizerRunner.ExecuteTokenizer(text);
        string[] tokens = tokenizedOutput.Split(' ');
        for (int i = 0; i < tokens.Length; i++) {
            if (tokens[i] == "")
            {
                tokens[i] = "0";
            };
        }
        int[] inputValues = tokens.Select(int.Parse).ToArray();
```

**Comment by mrwellmann** [comment]
You are welcome @beareality. I'm happy some found this useful 😄 
Thanks a lot for your suggestions! I had no time lately to continue my self on it.

I've implemented your changes in https://github.com/mrwellmann/Sentis-TTS-Test/pull/2/files and it sounds a lot better but something ist still not quiet right. 

Do you have an idea what I missed?

You can find the new output.wav at https://github.com/mrwellmann/Sentis-TTS-Test/blob/tokenization-fix/Assets/StreamingAssets/output.wav.

**Comment by mrwellmann** [comment]
Thanks was finished with help of https://github.com/mrwellmann/Sentis-TTS-Test/issues/3
